import type { Metadata } from "next";
import "./globals.css";
import { GeistSans } from "geist/font/sans";
import { GeistMono } from "geist/font/mono";
import { TooltipProvider } from '@/components/ui/tooltip';

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`font-sans antialiased ${GeistSans.variable} ${GeistMono.variable}`}
      >
        <TooltipProvider>
        <div className="flex flex-col min-h-screen">
          <main className="flex flex-col flex-1 bg-muted/50 dark:bg-background px-4">
            {children}
          </main>
        </div>
        </TooltipProvider>
      </body>
    </html>
  );
}
